settings:
  title: 'Status Page'
  url: 'https://status.dahyuk.workers.dev' # used for Slack messages
  logo: logo-192x192.png # image in ./public/ folder
  daysInHistogram: 90 # number of days you want to display in histogram
  collectResponseTimes: true # collects avg response times from CRON locations

  allmonitorsOperational: '모든 시스템 정상'
  notAllmonitorsOperational: '모든 시스템이 정상이 아님'
  monitorLabelOperational: '사용 가능'
  monitorLabelNotOperational: '사용 불가능'
  monitorLabelNoData: '기록 없음'
  dayInHistogramNoData: '기록 없음'
  dayInHistogramOperational: '좋음'
  dayInHistogramNotOperational: ' 사고(들)' # xx incident(s) recorded

monitors:
  - id: dhcloud # unique identifier
    name: DHCloud
    description: 'DHCloud - Archiving../' # default=empty
    url: 'https://cloud.dhweb.ml/' # URL to fetch
    method: GET # default=GET
    expectStatus: 200 # operational status, default=200
    followRedirect: false # should fetch follow redirects, default=false
    linkable: true # allows the title to be a link, default=true

  - id: dhweb-tk
    name: DHWeb
    description: 'DHWeb - Personal Blog'
    url: 'https://dhweb.tk/'
    method: GET
    expectStatus: 200
    linkable: true # allows the title to be a link, default=true

  - id: download-dhweb
    name: Download Proxy for DHWeb
    url: 'https://download.dhweb.tk/'
    method: GET
    expectStatus: 200
    linkable: true # allows the title to be a link, default=true
